name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'yandex-praktikum/hw05_final' }}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Git Clone Action
      uses: actions/checkout@v2
      with:
        repository: ${{ secrets.repository }}
        ssh-key: ${{ secrets.ACCESS_TOKEN }}
        path: yatube/
    - name: Lint with flake8 author
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 yatube --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 yatube --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics --config=setup.cfg
    - name: Lint with flake8 tests
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 tests --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 tests --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics
    - name: Test with pytest
      env:
        SECRET_KEY: "5UP3R-53CR3T-K3Y-FR0M-TurboKach"
        DJANGO_SETTINGS_MODULE: yatube.settings
        DEBUG: 1
        ALLOWED_HOSTS: "*"
      run: |
        py.test
